# Load environment variables from root directory .env
spring.config.import=optional:file:.env[.properties]

server.address=0.0.0.0
server.port=8080

# Database Configuration using Environment Variables
spring.datasource.url=jdbc:mysql://localhost:3306/cooksync_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Flyway Migration Configuration
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Custom JWT Property
jwt.secret=${JWT_SECRET}

logging.level.com.cooksync_server=INFO
logging.level.com.cooksync_server.config=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.boot=INFO
spring.main.log-startup-info=false
spring.main.banner-mode=off


